### ISSUE TITLE
Change database to PostgresSQL

### ISSUE THREAD

**Issue by eyobofficial** [eyobofficial/meteorology#3]
## Task
- [x] Install `psycopg2-binary` package using `pip` to connect to the PostgreSQL database
- [x] Update the `requirements/base.txt`
- [x] Update `.env_example` with the placeholder variables for the database credentials.
